// <auto-generated />
using System;
using MesAdmin.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MesAdmin.Infrastructure.Migrations
{
    [DbContext(typeof(MesDbContext))]
    [Migration("20260705123326_20260705_AddPreventiveMaintenance")]
    partial class _20260705_AddPreventiveMaintenance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MesAdmin.Domain.Models.AndonEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("AlarmType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CloseRemarks")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EquipmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("EscalatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("integer");

                    b.Property<string>("EventNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double?>("LowerLimit")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("NonConformanceReportId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessTag")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("ProcessValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Resolution")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Station")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double?>("UpperLimit")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentCode")
                        .HasDatabaseName("idx_andon_equipment");

                    b.HasIndex("EventNumber")
                        .IsUnique();

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("idx_andon_occurred");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_andon_status");

                    b.ToTable("andon_events", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.Bom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("EffectiveDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode", "Version")
                        .IsUnique();

                    b.ToTable("boms", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.ConsumptionVarianceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("ConsumedQuantity")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("StandardQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double>("VariancePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("VarianceQuantity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_variance_order");

                    b.ToTable("consumption_variance_reports", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.EightDReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ContainmentAction")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("ContainmentDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CorrectiveAction")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("CorrectiveActionDueDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CorrectiveActionOwner")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("NcrNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("NonConformanceReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreventiveAction")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ProblemDescription")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReportNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RootCause")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RootCauseAnalysis")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("TeamLeader")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TeamMembers")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("VerificationDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("VerificationMethod")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("VerificationResult")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ReportNumber")
                        .IsUnique();

                    b.ToTable("eight_d_reports", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.FirstArticleInspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Conclusion")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("InspectionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("InspectorId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.ToTable("first_article_inspections", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("ReceivedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("SapSynced")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("SapSyncedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("TraceabilityLabelCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("TraceabilityLabelCode")
                        .IsUnique();

                    b.ToTable("goods_receipts", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.HydraulicTestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer");

                    b.Property<string>("EquipmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("EquipmentLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double?>("HoldPressureBar")
                        .HasColumnType("double precision");

                    b.Property<bool?>("HoldPressurePass")
                        .HasColumnType("boolean");

                    b.Property<double?>("LeakRateCcHr")
                        .HasColumnType("double precision");

                    b.Property<bool?>("LeakRatePass")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OverallPass")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PressureBuildPass")
                        .HasColumnType("boolean");

                    b.Property<double?>("PressureBuildTimeMs")
                        .HasColumnType("double precision");

                    b.Property<bool?>("PressureReleasePass")
                        .HasColumnType("boolean");

                    b.Property<double?>("PressureReleaseTimeMs")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductSerial")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UnlockedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UnlockedBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentCode")
                        .HasDatabaseName("idx_hydraulic_equipment");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_hydraulic_order");

                    b.HasIndex("ProductSerial")
                        .HasDatabaseName("idx_hydraulic_serial");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_hydraulic_status");

                    b.ToTable("hydraulic_test_results", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.InspectionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AcceptNumber")
                        .HasColumnType("integer");

                    b.Property<double?>("AqlValue")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("EffectiveDate")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("EnableSpcChart")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("InspectionLevel")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("RejectNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<string>("SamplingFrequency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SpcSubgroupSize")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("Station")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .HasDatabaseName("idx_inspection_plan_product");

                    b.HasIndex("PlanName", "Version")
                        .IsUnique();

                    b.ToTable("inspection_plans", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.InventoryAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AlertLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<double>("CurrentQuantity")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("JitPullSignalId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("MinimumStock")
                        .HasColumnType("double precision");

                    b.Property<string>("Resolution")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("SafetyStock")
                        .HasColumnType("double precision");

                    b.Property<string>("StationId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AlertLevel")
                        .HasDatabaseName("idx_inv_alert_level");

                    b.HasIndex("MaterialCode")
                        .HasDatabaseName("idx_inv_alert_material");

                    b.ToTable("inventory_alerts", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.JitPullSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("DeliveredBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double>("ShortageQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TargetStation")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialCode")
                        .HasDatabaseName("idx_jit_pull_material");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_jit_pull_order");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_jit_pull_status");

                    b.ToTable("jit_pull_signals", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.MaintenancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("EquipmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastTriggeredAt")
                        .HasColumnType("timestamptz");

                    b.Property<long?>("LastTriggeredCycleCount")
                        .HasColumnType("bigint");

                    b.Property<int>("MaintenanceType")
                        .HasColumnType("integer");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("ThresholdValue")
                        .HasColumnType("double precision");

                    b.Property<string>("WorkContent")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentCode")
                        .HasDatabaseName("idx_mt_plan_equipment");

                    b.ToTable("maintenance_plans", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.MaintenanceWorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CompletionRemarks")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EquipmentCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("MaintenancePlanId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaintenanceType")
                        .HasColumnType("integer");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TriggerType")
                        .HasColumnType("integer");

                    b.Property<double>("TriggerValue")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentCode")
                        .HasDatabaseName("idx_mt_order_equipment");

                    b.HasIndex("MaintenancePlanId")
                        .HasDatabaseName("idx_mt_order_plan");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_mt_order_status");

                    b.ToTable("maintenance_work_orders", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.MaterialBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ProductionDate")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamptz");

                    b.Property<double>("ReceivedQuantity")
                        .HasColumnType("double precision");

                    b.Property<double>("RemainingQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("MaterialCode")
                        .HasDatabaseName("idx_material_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_material_status");

                    b.ToTable("material_batches", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.MaterialBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("BoundAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("MaterialBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PokaYokePassed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductSerial")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MaterialBatchId")
                        .HasDatabaseName("idx_binding_batch");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_binding_order");

                    b.HasIndex("ProductSerial")
                        .HasDatabaseName("idx_binding_serial");

                    b.ToTable("material_bindings", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.MaterialConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("ActualBoundQuantity")
                        .HasColumnType("double precision");

                    b.Property<double>("ConsumedQuantity")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("StandardQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<double>("VariancePercent")
                        .HasColumnType("double precision");

                    b.Property<double>("VarianceQuantity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MaterialCode")
                        .HasDatabaseName("idx_consumption_material");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_consumption_order");

                    b.HasIndex("OrderId", "MaterialCode")
                        .IsUnique()
                        .HasDatabaseName("ux_consumption_order_material");

                    b.ToTable("material_consumptions", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.MaterialInventorySetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("MinimumStock")
                        .HasColumnType("double precision");

                    b.Property<double>("SafetyStock")
                        .HasColumnType("double precision");

                    b.Property<string>("StationId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialCode")
                        .HasDatabaseName("idx_inv_setting_material");

                    b.HasIndex("StationId")
                        .HasDatabaseName("idx_inv_setting_station");

                    b.ToTable("material_inventory_settings", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.NonConformanceReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CloseRemarks")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("DefectQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("DiscoveredAt")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("DiscoveredBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Disposition")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("DispositionDeadline")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("EightDReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("NcrNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("QualityRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponsibleDept")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ReviewComments")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ReviewerId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .HasDatabaseName("idx_ncr_batch");

                    b.HasIndex("NcrNumber")
                        .IsUnique();

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_ncr_order");

                    b.HasIndex("ProductCode")
                        .HasDatabaseName("idx_ncr_product");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_ncr_status");

                    b.ToTable("non_conformance_reports", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.ProductionOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActualEndAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("ActualStartAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("BomVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("DefectiveQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalOrderNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("LineId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("PlannedEndAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PlannedStartAt")
                        .HasColumnType("timestamptz");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("QualifiedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoutingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Shift")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("WorkCenterId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_orders_created_at");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_orders_status");

                    b.ToTable("production_orders", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.QualityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AcceptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("AqlScheme")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("DefectCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("InspectionPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("InspectionPlanName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InspectorId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RejectNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SupplierCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .HasDatabaseName("idx_quality_batch");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_quality_order");

                    b.HasIndex("ProductCode")
                        .HasDatabaseName("idx_quality_product");

                    b.HasIndex("Stage")
                        .HasDatabaseName("idx_quality_stage");

                    b.ToTable("quality_records", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.SapInventorySyncRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<string>("SapDocumentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("SapSynced")
                        .HasColumnType("boolean");

                    b.Property<string>("SyncError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("SyncedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialCode")
                        .HasDatabaseName("idx_sap_inv_sync_material");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_sap_inv_sync_order");

                    b.HasIndex("SapSynced")
                        .HasDatabaseName("idx_sap_inv_sync_status");

                    b.ToTable("sap_inventory_sync_records", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.SapRejectionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BomVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExternalOrderNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("RejectedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("RejectionReason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RoutingId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("WritebackAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("WritebackError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("WritebackStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalOrderNumber")
                        .HasDatabaseName("idx_sap_rejection_external");

                    b.HasIndex("WritebackStatus")
                        .HasDatabaseName("idx_sap_rejection_writeback");

                    b.ToTable("sap_rejection_records", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.SpcRuleAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("AlertLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CharacteristicCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EquipmentCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("RuleType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TriggerSubgroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicCode")
                        .HasDatabaseName("idx_spc_alert_char");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_spc_alert_created");

                    b.ToTable("spc_rule_alerts", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.SpcSample", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacteristicCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CollectedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("EquipmentCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Mean")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<double>("Range")
                        .HasColumnType("double precision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<double>("StdDev")
                        .HasColumnType("double precision");

                    b.Property<int>("SubgroupIndex")
                        .HasColumnType("integer");

                    b.Property<int>("SubgroupSize")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string>("Values")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicCode")
                        .HasDatabaseName("idx_spc_characteristic");

                    b.HasIndex("CollectedAt")
                        .HasDatabaseName("idx_spc_collected_at");

                    b.HasIndex("EquipmentCode")
                        .HasDatabaseName("idx_spc_equipment");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_spc_order");

                    b.HasIndex("SubgroupIndex")
                        .HasDatabaseName("idx_spc_subgroup");

                    b.HasIndex("CharacteristicCode", "SubgroupIndex")
                        .IsUnique();

                    b.ToTable("spc_samples", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.TraceabilityLink", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentBatch")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialBatch")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VinOrSerial")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentBatch")
                        .HasDatabaseName("idx_trace_component");

                    b.HasIndex("MaterialBatch")
                        .HasDatabaseName("idx_trace_material");

                    b.HasIndex("VinOrSerial")
                        .HasDatabaseName("idx_trace_vin");

                    b.HasIndex("VinOrSerial", "Level")
                        .IsUnique();

                    b.ToTable("traceability_links", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.WorkOrderOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("EndAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("EquipmentId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OperationCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OperatorId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarks")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Station")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "Sequence")
                        .IsUnique();

                    b.ToTable("work_order_operations", (string)null);
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.Bom", b =>
                {
                    b.OwnsMany("MesAdmin.Domain.Models.BomItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("BomId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("IsCritical");

                            b1.Property<int>("Level");

                            b1.Property<string>("MaterialCode")
                                .IsRequired();

                            b1.Property<string>("MaterialName")
                                .IsRequired();

                            b1.Property<string>("ParentMaterialCode");

                            b1.Property<double>("QuantityPerUnit");

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.HasKey("BomId", "__synthesizedOrdinal");

                            b1.ToTable("boms");

                            b1
                                .ToJson("Items")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BomId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.FirstArticleInspection", b =>
                {
                    b.OwnsMany("MesAdmin.Domain.Models.InspectionItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("FirstArticleInspectionId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double?>("ActualValue");

                            b1.Property<string>("CharacteristicCode")
                                .IsRequired();

                            b1.Property<string>("CharacteristicName")
                                .IsRequired();

                            b1.Property<string>("InspectionTool");

                            b1.Property<bool>("IsPass");

                            b1.Property<double?>("LowerLimit");

                            b1.Property<string>("Remarks");

                            b1.Property<double>("StandardValue");

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.Property<double?>("UpperLimit");

                            b1.HasKey("FirstArticleInspectionId", "__synthesizedOrdinal");

                            b1.ToTable("first_article_inspections");

                            b1
                                .ToJson("Items")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("FirstArticleInspectionId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.HydraulicTestResult", b =>
                {
                    b.OwnsMany("MesAdmin.Domain.Models.SolenoidValveTest", "SolenoidTests", b1 =>
                        {
                            b1.Property<Guid>("HydraulicTestResultId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<bool>("ActuationPass");

                            b1.Property<double?>("CoilResistance");

                            b1.Property<string>("FaultCode")
                                .HasMaxLength(16);

                            b1.Property<double>("ResponseTimeMs");

                            b1.Property<int>("ValveIndex");

                            b1.HasKey("HydraulicTestResultId", "__synthesizedOrdinal");

                            b1.ToTable("hydraulic_test_results");

                            b1
                                .ToJson("SolenoidTests")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HydraulicTestResultId");
                        });

                    b.Navigation("SolenoidTests");
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.InspectionPlan", b =>
                {
                    b.OwnsMany("MesAdmin.Domain.Models.PlanCharacteristic", "Characteristics", b1 =>
                        {
                            b1.Property<Guid>("InspectionPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double?>("CenterLine");

                            b1.Property<double?>("CenterRange");

                            b1.Property<string>("CharacteristicCode")
                                .IsRequired()
                                .HasMaxLength(32);

                            b1.Property<string>("CharacteristicName")
                                .IsRequired()
                                .HasMaxLength(64);

                            b1.Property<bool>("EnableSpc");

                            b1.Property<bool>("IsCritical");

                            b1.Property<double?>("LowerControlLimit");

                            b1.Property<double?>("LowerSpecLimit");

                            b1.Property<string>("MeasurementTool")
                                .HasMaxLength(32);

                            b1.Property<double>("StandardValue");

                            b1.Property<int>("Type");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(16);

                            b1.Property<double?>("UpperControlLimit");

                            b1.Property<double?>("UpperRangeLimit");

                            b1.Property<double?>("UpperSpecLimit");

                            b1.HasKey("InspectionPlanId", "__synthesizedOrdinal");

                            b1.ToTable("inspection_plans");

                            b1
                                .ToJson("Characteristics")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("InspectionPlanId");
                        });

                    b.Navigation("Characteristics");
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.QualityRecord", b =>
                {
                    b.OwnsMany("MesAdmin.Domain.Models.MeasuredCharacteristic", "Characteristics", b1 =>
                        {
                            b1.Property<Guid>("QualityRecordId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double?>("ActualValue");

                            b1.Property<string>("CharacteristicCode")
                                .IsRequired()
                                .HasMaxLength(32);

                            b1.Property<string>("CharacteristicName")
                                .IsRequired()
                                .HasMaxLength(64);

                            b1.Property<bool>("IsFailed");

                            b1.Property<double?>("LowerSpecLimit");

                            b1.Property<string>("MeasurementTool")
                                .HasMaxLength(32);

                            b1.Property<double>("StandardValue");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(16);

                            b1.Property<double?>("UpperSpecLimit");

                            b1.HasKey("QualityRecordId", "__synthesizedOrdinal");

                            b1.ToTable("quality_records");

                            b1
                                .ToJson("Characteristics")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("QualityRecordId");
                        });

                    b.Navigation("Characteristics");
                });

            modelBuilder.Entity("MesAdmin.Domain.Models.WorkOrderOperation", b =>
                {
                    b.OwnsMany("MesAdmin.Domain.Models.ProcessParameter", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("WorkOrderOperationId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<double?>("ActualValue");

                            b1.Property<bool?>("IsPass");

                            b1.Property<double?>("LowerLimit");

                            b1.Property<string>("ParameterCode")
                                .IsRequired();

                            b1.Property<string>("ParameterName")
                                .IsRequired();

                            b1.Property<DateTimeOffset?>("RecordedAt");

                            b1.Property<double>("StandardValue");

                            b1.Property<string>("Unit")
                                .IsRequired();

                            b1.Property<double?>("UpperLimit");

                            b1.HasKey("WorkOrderOperationId", "__synthesizedOrdinal");

                            b1.ToTable("work_order_operations");

                            b1
                                .ToJson("Parameters")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorkOrderOperationId");
                        });

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
